/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_openml_jni_JEnv */

#ifndef _Included_com_openml_jni_JEnv
#define _Included_com_openml_jni_JEnv
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_openml_jni_JEnv
 * Method:    setupJni
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/Object;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_openml_jni_JEnv_setupJni
  (JNIEnv *, jclass, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
